### ISSUE TITLE
ApplicationHooks have inconsistent reference to instance

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify#4967]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

While looking at the onListen hook PR, I realized it is not that strict on how the application hooks refer to the instance. 

- `onRoute` has the reference to the `instance` in the `this` parameter.
- `onRegister` has the reference to the `instance` in the `instance` parameter.
- `onClose` has the reference to the `instance` in the `instance` parameter.
- `onReady` has the reference to the `instance` in the `this` reference
- `preClose` has the reference to the `instance` in the `this` reference

I dont see any pattern. 
```[tasklist]
### Tasks
- [ ] https://github.com/fastify/fastify/pull/4972
```

**Comment by metcoder95** [comment]
I believe that the only two that differ from the rest are the only ones handled through `avvio` and are not yet monkey-patched: https://github.com/fastify/fastify/blob/c235d2dc136a67c51095f188742c743d8cb32839/fastify.js#L404-L410

If looking to standardise all, it might be interesting to see if we can make all the ones provided by `avvio` be customized easily as we did for `onReady` - https://github.com/fastify/fastify/blob/c235d2dc136a67c51095f188742c743d8cb32839/fastify.js#L557

**Comment by Uzlopak** [comment]
Which pattern we should prefer? :d

**Comment by Eomm** [comment]
I like the `this` one

**Comment by Uzlopak** [comment]
Should we target v5 with this?

**Comment by metcoder95** [comment]
> I like the `this` one

+1

**Comment by Uzlopak** [comment]
I personally prefer the instance parameter, because it is more obvious than the need to read in the docs that this points to the instance. 

But dont worry, i have not a strong opinion on this topic.

Consistence is imho more important.

I will provide a PR and target next.

**Comment by climba03003** [comment]
> I personally prefer the instance parameter, because it is more obvious than the need to read in the docs that this points to the instance.

I prefer both should be exist.
When referencing `this` binding only, it is actually restricting the user to never use `lamda` function.

**Comment by mcollina** [comment]
> I prefer both should be exist.
When referencing this binding only, it is actually restricting the user to never use lamda function.

I agree.

**Comment by metcoder95** [comment]
> > I personally prefer the instance parameter, because it is more obvious than the need to read in the docs that this points to the instance.
> 
> I prefer both should be exist. When referencing `this` binding only, it is actually restricting the user to never use `lamda` function.

Good point, also noticed that some hooks seems to require being this explicit because of the scope of the hook

**Comment by Uzlopak** [comment]
Sure. Then instance everywhere and bind this?

**Comment by mcollina** [comment]
I think it's better, yes

**Comment by jsumners** [comment]
If we are going to change signatures, may I suggest we go for parameter objects at the same time?

-----

<details>
<summary>benchmark.js</summary>

```js
'use strict'

const Benchmark = require('benchmark')
const suite = new Benchmark.Suite()

suite.add('boundThis', () => {
  const instance = { x: 0 }
  boundThis.call(instance, { y: 1 })
})

suite.add('paramOnly', () => {
  const instance = { x: 0 }
  paramOnly({ y: 1 }, instance)
})

suite.add('boundThisAndParam', () => {
  const instance = { x: 0 }
  boundThisAndParam.call(instance, { y: 1 }, instance)
})

suite.add('boundThisAndParamsObject', () => {
  const instance = { x: 0 }
  const options = { y: 1 }
  boundThisAndParamsObject.call(instance, { options, instance })
})

suite.add('paramsObjectOnly', () => {
  const instance = { x: 0 }
  const options = { y: 1 }
  paramsObjectOnly({ options, instance })
})

suite
  .on('cycle', (event) => {
    console.log(String(event.target))
  })
  .on('complete', function () {
    console.log('Fastest is: ' + this.filter('fastest').map('name'))
  })
  .run({ async: true })

// The following functions are modeled after the `onRoute` hook function signature.

function boundThis(options) {
  return this.x + 1 + (options?.y || 0)
}

function paramOnly(options, instance) {
  return instance.x + 1 + (options?.y || 0)
}

function boundThisAndParam(options, instance) {
  return instance.x + 1 + (options?.y || 0)
}

function boundThisAndParamsObject({ options, instance }) {
  return instance.x + 1 + (options?.y || 0)
}

function paramsObjectOnly({ options, instance }) {
  return instance.x + 1 + (options?.y || 0)
}
```

</details>

<details>
<summary>Results</summary>

On my M1 Max with 32GB RAM (and a lot of other things running), with Node 18.17.0, I get:

```sh
boundThis x 369,407,621 ops/sec ±0.55% (93 runs sampled)
paramOnly x 1,028,874,034 ops/sec ±0.13% (101 runs sampled)
boundThisAndParam x 349,017,336 ops/sec ±1.01% (96 runs sampled)
boundThisAndParamsObject x 376,280,603 ops/sec ±0.60% (93 runs sampled)
paramsObjectOnly x 1,029,073,719 ops/sec ±0.08% (97 runs sampled)
Fastest is: paramsObjectOnly,paramOnly
```


</details>

**Comment by climba03003** [comment]
The below results show that `boundThisAndParam` is slightly faster than `boundThisParamsObject` on x86 platform.
The result from Node.js 20 is showing all of them has no observable different.
I assume v8 has optimized all the use-case so they becomes all fast.

<details>

<summary>Node.js 20.5.1 on i9-13900H 48GB Windows 11 Pro</summary>

```
boundThis x 1,081,203,601 ops/sec ±1.77% (91 runs sampled)
paramOnly x 1,070,557,909 ops/sec ±2.19% (87 runs sampled)
boundThisAndParam x 1,068,928,283 ops/sec ±2.01% (85 runs sampled)
boundThisAndParamsObject x 1,046,852,186 ops/sec ±4.12% (87 runs sampled)
paramsObjectOnly x 1,067,702,617 ops/sec ±2.91% (89 runs sampled)
Fastest is: boundThis,boundThisAndParam,paramOnly,paramsObjectOnly,boundThisAndParamsObject
```

</details>

<details>

<summary>Node.js 18.17.1 on i9-13900H 48GB Windows 11 Pro</summary>

```
boundThis x 207,636,672 ops/sec ±3.12% (82 runs sampled)
paramOnly x 986,820,501 ops/sec ±4.82% (78 runs sampled)
boundThisAndParam x 126,834,807 ops/sec ±3.69% (70 runs sampled)
boundThisAndParamsObject x 119,622,176 ops/sec ±3.77% (81 runs sampled)
paramsObjectOnly x 613,040,836 ops/sec ±1.09% (81 runs sampled)
Fastest is: paramOnly
```

</details>

**Comment by jsumners** [comment]
Node 18 is very likely going to be the minimum supported version for the next LTS. I think all of the posted benchmark results show that `boundThisAndParamsObject` is sufficiently "fast" and not a significant enough "slow down" to avoid.

**Comment by arthurfiorette** [comment]
Hey, any updated on this?

**Comment by gurgunday** [comment]
@Uzlopak is busy at the moment AFAIK, so someone could take over I think

I can look at this after Wednesday

**Comment by Eomm** [comment]
Updated the first comment with the discussion's outcome

**Comment by mcollina** [comment]
@Uzlopak would you like to send a PR for this? I plan to ship v5 in a couple of weeks.

**Comment by Uzlopak** [comment]
I think @Eomm mentioned, that this and instance would actually point to different instances. Wasnt there something?

**Comment by Eomm** [comment]
> Wasnt there something?

Mmm, can't recall it - but a working code is always the best

**Comment by gurgunday** [comment]
> Document the this context more clearly for every hook

Writing this comment to not forget where we are in case #5675 doesn't make it to v5

With #5675, all the hooks mentioned here will have `this` pointing to the instance from which they were registered, so that part will be complete

We can then focus on the parameters, and we agreed on `boundThisAndParamsObject.call(instance, { options, instance })`

For now, I don't know what we agreed on in the case of  `onRegister` - here are 2 ways it could be:

- `{ options, instance }` with `instance` pointing to the new instance and `this` pointing to the parent

or:

- `{ options, instance, newInstance}` with `this` pointing to the parent

**Comment by Uzlopak** [comment]
What a bees nest 🙈

**Comment by rafay247** [comment]
Hi, I would like to work on this issue.

**Comment by metcoder95** [comment]
Go for it, take into consideration the discussion of this thread

**Comment by MakenRosa** [comment]
I would make the first implementation target the agreed `boundThisAndParamsObject` shape and resolve `onRegister` explicitly, because that is the only place where parent/child ambiguity can leak into the API.

Proposed contract:

- For every application hook, call the handler with `this` bound to the instance that registered the hook.
- Pass a single object argument.
- Include `instance` in that object as the same instance as `this`, so arrow functions have an explicit equivalent.
- For `onRegister`, pass `{ instance, newInstance, options }`, where `instance` is the parent/registration instance and `newInstance` is the child plugin instance.

Implementation steps:

1. Add a small internal invocation helper for application hooks so the binding/object shape is centralized.
2. Update one hook group at a time, starting with `onRegister` because it needs the explicit `newInstance` naming.
3. Add tests asserting both `this` and object refs for normal functions and arrow functions.
4. Update TypeScript definitions and the migration/docs note in the same PR.

That keeps the breaking API shape consistent while preserving an explicit parent reference for lambda users.

**Comment by metcoder95** [comment]
>Pass a single object argument.

I'm not fully convinced of changing the contract to a single object, the current positional args usually provides the required objects to achieve what the hook is intended to do, changing it without an intention of extending it further seems like an unneeded change.

I'd advice to keep the positional while achieving the standardisation of the `this` context.

Looking forward for the PR

**Comment by mv-estrela** [comment]
I would like to work on this. I've gone through the full thread, the closed PRs (#6557, #6798, #6761), and the merged #5675 which already standardized this binding.
The remaining work is standardizing the parameters, but I see a disagreement on the approach:
- Earlier consensus (mcollina, climba03003, jsummers): boundThisAndParamsObject.call(instance, { options, instance })
- Recent feedback (@metcoder95): keep positional args, the object change is unnecessary

Before I start, could you clarify which direction to take?

**Comment by mv-estrela** [comment]
I've implemented the parameter standardization for all six application hooks.

PR: https://github.com/fastify/fastify/pull/6992

This PR takes the positional approach, which means that every hook now receives instance as the first parameter, with this also bound to the same instance:

- onRoute(instance, routeOptions)
- onRegister(instance, newInstance, opts)
- onReady(instance, done)
- onListen(instance, done)
- preClose(instance, done)
- onClose(instance, done)

onRegister receives newInstance as second parameter for parent/child disambiguation, but instance is always the parent (same as this), newInstance is the child plugin instance.

Changes include updated hook runners, validation adjustments, and tests covering both function and arrow function usage for all hooks.

I also have an object-based implementation ({ instance, ... }) ready on a separate branch, following the boundThisAndParamsObject shape discussed earlier in this thread. Happy to open that as an alternative PR if preferred.

**Comment by LeonxLJX** [comment]
I'd like to take this one (`ApplicationHooks have inconsistent reference to instance`). I'll look into the root cause and follow up with a PR. (claiming via @LeonxLJX)

**Comment by LeonxLJX** [comment]
I'd like to take this one (`ApplicationHooks have inconsistent reference to instance`). I'll look into the root cause and follow up with a PR. (claiming via @LeonxLJX)
