### ISSUE TITLE
Fastify logo link broken in readme.md

### ISSUE THREAD

**Issue by Subhahdip** [fastify/fastify#5172]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Node.js version

20.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

The logo link in the readme file is not valid.

### Steps to Reproduce

Go the the readme.md page on github

### Expected Behavior

It should have a logo of fastify
```[tasklist]
### Tasks
- [ ] https://github.com/fastify/fastify/pull/5173
```

**Comment by mcollina** [comment]
It seems that the links work correctly for me.

**Comment by Uzlopak** [comment]
Seems to me that this is some late hacktober issue.

![Screenshot_20231125-162022_Chrome](https://github.com/fastify/fastify/assets/5059100/786544bc-57cd-4871-a484-0ca0a48ac66c)

**Comment by Subhahdip** [comment]
@mcollina @Uzlopak could be a problem from my browser end. Just rechecked and it still shows a broken link
![Screenshot (6)](https://github.com/fastify/fastify/assets/87298461/e7442646-e148-403b-a301-71bbdf2de4b8)

**Comment by Uzlopak** [comment]
Maybe your adblocker blocks it
