### ISSUE TITLE
Refactor Documentation

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify#577]
## Fastify Documentation Refactor
Ref #229 #296 

### Goal
This issue should accurately describe and track all upcoming changes for Fastify documentation in preparation for the v1.0.0 release (this will not block the 1.0.0 release). 
> documentation is serviceable for v1.0.0 @jsumners https://github.com/fastify/fastify/issues/229#issuecomment-353644261

### Comments
> we have mixed the classic "Getting started" documentation with the classic "API Reference": some piece of documentation is written for learning fastify (like Middleware); other to list the options (like Server Method); other a mixin (like Reply). This is a mess.
@allevo: https://github.com/fastify/fastify/issues/296#issue-260047107

> One method would be how I refactored Pino's documentation -- https://github.com/pinojs/pino I see Readme documents as introductions. They should not be the reference documentation for a large project. So I broke it up into parts, but made one big "jsdoc style" API document -- https://github.com/pinojs/pino/blob/master/docs/API.md . This gave us several documents, all linked from the Readme, that describe things with examples and a single place to go to for the gritty details.
@jsumners: https://github.com/fastify/fastify/issues/296#issuecomment-331678707

> Fastify's an outstanding framework, and I love its performance-first priorities. However, I've had to consult the source code a few times to debug misunderstandings that should ideally be covered in the docs. Love the idea of a split between a set of introductory, 'getting started'-style docs with trivial examples and a comprehensive API spec.
@gj https://github.com/fastify/fastify/issues/296#issuecomment-337361893

> hapi tutorials part is something that I'd love to see in fastify 
 @yamalight: https://github.com/fastify/fastify/issues/296#issuecomment-353655031

Based on the previous comments regarding the documentation I have set out the following list of todo items:

### ToDo
- [ ] Create Tutorial section (including Beginner Getting Started)
- [ ] Create various tutorials for Tutorial section in order to cover a majority of Fastify use cases.
  One that I have in mind is a section on serving static files with Fastify. This process is documented under `fastify-static`; however, if a user is unfamiliar with the ecosystem plugins they will be lost (like I was temporarily trying to figure this exact use case out!)
- [ ] Create detailed API spec 
- [ ] Proofread Ecosystem documentation.
  The ecosystem plugins are very well documented already, but we should pay some attention to them while we refactor the documentation. All plugins should have links back to the main documentation and ideally tutorials in the Tutorial section as well.
- [ ] Review Quick Start section on website home page. 

The API spec should cover the entire library. We need to remove the necessity of reading source code. 

### Footnote
This is a discussion based issue; I encourage you to share your thoughts and opinions. We need to provide the best documentation as possible without going overboard. The larger the documentation the more to maintain as new versions of Fastify are released.

**Comment by Ethan-Arrowood** [comment]
## API Documentation Mockup
![documentation section](https://user-images.githubusercontent.com/16144158/34312616-6f4ffe52-e733-11e7-9853-77230f1a84e8.png)
I'm a huge fan of Node.js [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_connect) as well as Mozilla's [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype). The API Documentation will be heavily based off what we currently have, plus everything else in the source code. This section should be a lot more 'techy' and I'd even go as far as including TypeScript definitions as seen [here](https://github.com/jaredpalmer/formik#formik-props) in the Formik documentation. 

This would provide the best developer experience as the more information we can share about the Fastify methods, the less the developer will need to read source code.

## Tutorial Mockup
![tutorial section](https://user-images.githubusercontent.com/16144158/34312618-6f5a84c6-e733-11e7-9454-ca65894ca6d6.png)

Based off of Hapi [tutorials](https://hapijs.com/tutorials) this section would cover as many general cases as possible. As a challenge down the road we could actually include a full tutorial like [Gatsby](https://www.gatsbyjs.org/tutorial/)

**Comment by jsumners** [comment]
Wow! I am already very impressed. I look forward to seeing what you come up with.

**Comment by mcollina** [comment]
I’m very impressed :). Let us know if you need any help!

**Comment by Ethan-Arrowood** [comment]
I think I'll need some help with the API Spec, but I'll make sure to post specific questsions/issues when I come accros them

**Comment by Ethan-Arrowood** [comment]
@mcollina I think I'm going to need some help with the website. I tried making a tutorial page but I'm having some trouble understanding handlebars as well as the build scripts. Do you have any recommendations on how to proceed?

**Comment by delvedor** [comment]
@Ethan-Arrowood you should speak with @lmammino :)

**Comment by delvedor** [comment]
I'm working on a Fastify workshop, I'm going to finish it during the holidays :)

**Comment by mcollina** [comment]
@Ethan-Arrowood It would be better to file a PR with the non-working code and print an error. Or if you have some more specific questions, open issues!

**Comment by jsumners** [comment]
I would focus first on the documentation within this repository. The website can be updated afterward.

**Comment by jsumners** [comment]
> This section should be a lot more 'techy' and I'd even go as far as including TypeScript definitions as seen here in the Formik documentation.

I'd really rather see something like https://getpino.io/#/docs/API?id=childbindings or https://github.com/jscas/cas-server/blob/128a8d4def29c9a1a5092312c15dec3e70e8c930/docs/Plugins.md#serviceregistry-plugins . I find the TS stuff too difficult to read (I can't express my level of frustration when I try to navigate to a module's source code in VSCode and get taken to a TS definition).

**Comment by jsumners** [comment]
Regarding tutorials, Choo has some good stuff:

+ https://choo.io/
+ https://handbook.choo.io/
+ https://avocado.choo.io/01-choo

**Comment by Ethan-Arrowood** [comment]
I started working on the API spec this evening. I got a basic set up started and will continue to make edits on this file. I'll open a PR when I get this further developed and I believe it's ready for feedback. https://github.com/Ethan-Arrowood/fastify/blob/improve-documentation/docs/Fastify.md

**Comment by jsumners** [comment]
Personally, I like that format and think it's looking great.

I suggest adding a `<a id="#foo"></a>` before each heading. This will allow you to add a table of contents, as well as easily link to specific sections throughout the documentation.

**Comment by jsumners** [comment]
diff --git a/docs/Fastify.md b/docs/Fastify.md
    index da11bb7..e9f9d70 100644
    --- a/docs/Fastify.md
    +++ b/docs/Fastify.md
    @@ -2,13 +2,16 @@

     ## module.exports

    +<a id="fastifyFactory"></a>
     ## .build([options])

    +Returns a new *Fastify* [server](#server) instance.
    +
     ### Parameters
     - options (object):
       - logger (boolean): Toggles `Logger` utility. Default `false`.
       - http2 (boolean): Toggles experimental HTTP2 features. Default `false`.
    -  - https (object):
    +  - https (object):
         - allowHTTP1 (boolean): Toggles `HTTP/1` usage
         - key (string): `HTTPS/2` security key
         - cert (string): `HTTPS/2` security certificate
    @@ -27,12 +30,16 @@ cosnt fastify = require('fastify')({
     })
     ```

    +<a id="server"></a>
     ## Server Methods

    +<a id="serverListen"></a>
     ## .listen(port, [address,] [callback])
     Starts the server on the given port after all the plugins are loaded, internally waits for the .ready() event. The callback is the same as the Node core.

    +<a id="serverReady"></a>
     ## ready([callback])
    -Function called when all the plugins have been loaded. Returns a `Promise` if no callback is specified.
    +Function called when all the plugins have been loaded. Returns a `Promise` if no callback is specified.

    -## route(options)
    \ No newline at end of file
    +<a id="serverRoute"></a>
    +## route(options)

**Comment by Ethan-Arrowood** [comment]
Awesome sounds good. I'll keep working on this and add the a tags.

**Comment by lmammino** [comment]
A bit late to the party here, but this looks like an awesome idea :) let me know if you need any help from the perspective of the website 😉

**Comment by Ethan-Arrowood** [comment]
I've just been working on making a API spec markdown file. Trying to make my way through the current docs and then compare with the source code to make sure all parameters are properly articulated in the documentation.

**Comment by israeleriston** [comment]
great!! this is going to be amazing, I'm ready to help.

**Comment by Ethan-Arrowood** [comment]
I've lost my vision for this update. If someone wants to pick it up feel free to. I think slowly adding bits and pieces to the documentation where we notice things are missing is better than trying to overhaul the entire thing. for example ref #841

**Comment by jsumners** [comment]
I think that was my original suggestion 😉.
